# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8eafa31520b8e614d00b94633b709b465de2552ff7cf704c10c91f932384aecc06c4b33049890447358306d200deb9ac673b06890908ffdfc1a444071bb6ff8

test:
  secret_key_base: bdd231731e1db49422ae1ffad05e77b8f799afc9b1748fc10591e3261ed7d62ca6ca70ee33fa6d388757386ff6d5485d9bd8e131127d46b5512794dc2c3961ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
